-- Verificación de migraciones aplicadas.
-- Pegar entero en Supabase → SQL Editor y correr. Devuelve una fila por
-- migración con el estado de un objeto representativo de cada una:
--   OK    → el objeto existe (la migración está aplicada)
--   FALTA → no existe (probablemente falta correr esa migración)
-- Es solo lectura, no modifica nada. Ordena por migración.
--
-- Nota: chequea UN objeto clave por migración (no todo su contenido), así que
-- "OK" = casi seguro aplicada; "FALTA" = seguro falta (o se aplicó a medias).

with checks(mig, objeto, existe) as (
  values
    ('00002', 'profiles.zone (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='profiles' and column_name='zone'))),
    ('00005', 'tabla feature_suggestions',
      (to_regclass('public.feature_suggestions') is not null)),
    ('00006', 'tabla favorites',
      (to_regclass('public.favorites') is not null)),
    ('00006', 'tabla notifications',
      (to_regclass('public.notifications') is not null)),
    ('00007', 'listings.sold_to (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='listings' and column_name='sold_to'))),
    ('00009', 'listings.lat (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='listings' and column_name='lat'))),
    ('00010', 'listings.favorites_count (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='listings' and column_name='favorites_count'))),
    ('00010', 'listings.previous_price (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='listings' and column_name='previous_price'))),
    ('00011', 'tabla saved_searches',
      (to_regclass('public.saved_searches') is not null)),
    ('00012', 'enum listing_status = reserved',
      (exists (select 1 from pg_enum e join pg_type t on t.oid=e.enumtypid where t.typname='listing_status' and e.enumlabel='reserved'))),
    ('00012', 'listings.views_count (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='listings' and column_name='views_count'))),
    ('00012', 'RPC increment_listing_views',
      (exists (select 1 from pg_proc where proname='increment_listing_views'))),
    ('00013', 'messages.image_path (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='messages' and column_name='image_path'))),
    ('00014', 'RPC conversation_previews',
      (exists (select 1 from pg_proc where proname='conversation_previews'))),
    ('00014', 'tabla listing_views',
      (to_regclass('public.listing_views') is not null)),
    ('00015', 'profiles.last_seen_at (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='profiles' and column_name='last_seen_at'))),
    ('00017', 'listings.is_auction (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='listings' and column_name='is_auction'))),
    ('00017', 'tabla bids',
      (to_regclass('public.bids') is not null)),
    ('00017', 'RPC place_bid',
      (exists (select 1 from pg_proc where proname='place_bid'))),
    ('00017', 'RPC close_auctions',
      (exists (select 1 from pg_proc where proname='close_auctions'))),
    ('00017', 'RPC reassign_auction',
      (exists (select 1 from pg_proc where proname='reassign_auction'))),
    ('00018', 'categoría plantas-jardineria',
      (exists (select 1 from categories where slug='plantas-jardineria'))),
    ('00019', 'tabla push_subscriptions',
      (to_regclass('public.push_subscriptions') is not null)),
    ('00020', 'categoría alquileres',
      (exists (select 1 from categories where slug='alquileres'))),
    ('00021', 'messages.edited_at (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='messages' and column_name='edited_at'))),
    ('00021', 'RPC edit_message',
      (exists (select 1 from pg_proc where proname='edit_message'))),
    ('00021', 'RPC delete_message',
      (exists (select 1 from pg_proc where proname='delete_message'))),
    ('00022', 'función num_from_text',
      (exists (select 1 from pg_proc where proname='num_from_text'))),
    ('00022', 'listings.veh_anio (columna generada)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='listings' and column_name='veh_anio'))),
    ('00022', 'listings.inmueble_sup (columna generada)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='listings' and column_name='inmueble_sup'))),
    ('00023', 'notifications.actor_id (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='notifications' and column_name='actor_id'))),
    ('00024', 'profiles.is_admin (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='profiles' and column_name='is_admin'))),
    ('00024', 'función is_admin()',
      (exists (select 1 from pg_proc where proname='is_admin'))),
    ('00024', 'enum report_target = message',
      (exists (select 1 from pg_enum e join pg_type t on t.oid=e.enumtypid where t.typname='report_target' and e.enumlabel='message'))),
    ('00025', 'profiles.auction_strikes (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='profiles' and column_name='auction_strikes'))),
    ('00025', 'listings.buyer_confirmed_pickup (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='listings' and column_name='buyer_confirmed_pickup'))),
    ('00025', 'RPC confirm_auction_pickup',
      (exists (select 1 from pg_proc where proname='confirm_auction_pickup'))),
    ('00025', 'RPC report_auction_no_show',
      (exists (select 1 from pg_proc where proname='report_auction_no_show'))),
    ('00026', 'RPC recommended_listings',
      (exists (select 1 from pg_proc where proname='recommended_listings'))),
    ('00027', 'conversations.listing_id es nullable',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='conversations' and column_name='listing_id' and is_nullable='YES'))),
    ('00029', 'enum report_target = support',
      (exists (select 1 from pg_enum e join pg_type t on t.oid=e.enumtypid where t.typname='report_target' and e.enumlabel='support'))),
    ('00030', 'conversations.kind (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='conversations' and column_name='kind'))),
    ('00030', 'RPC send_welcome_dm',
      (exists (select 1 from pg_proc where proname='send_welcome_dm'))),
    ('00030', 'trigger on_profile_welcome',
      (exists (select 1 from pg_trigger where tgname='on_profile_welcome'))),
    ('00031', 'tabla signup_surveys',
      (to_regclass('public.signup_surveys') is not null)),
    ('00032', 'trigger on_question_notify',
      (exists (select 1 from pg_trigger where tgname='on_question_notify'))),
    ('00033', 'place_bid con anti-snipe (extiende el cierre)',
      (exists (select 1 from pg_proc where proname='place_bid' and prosrc like '%30 seconds%'))),
    ('00034', 'listings.inm_dormitorios (columna generada)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='listings' and column_name='inm_dormitorios'))),
    ('00035', 'listings.auction_min_increment (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='listings' and column_name='auction_min_increment'))),
    ('00036', 'formas_de_pago en required_fields',
      (exists (select 1 from public.categories where required_fields::text like '%formas_de_pago%'))),
    ('00037', 'profiles.terms_accepted_at (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='profiles' and column_name='terms_accepted_at'))),
    ('00038', 'profiles.account_restricted (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='profiles' and column_name='account_restricted'))),
    ('00039', 'trigger on_rating_visible_recalc',
      (exists (select 1 from pg_trigger where tgname='on_rating_visible_recalc'))),
    ('00040', 'RPC listings_near',
      (exists (select 1 from pg_proc where proname='listings_near'))),
    ('00041', 'RPC relaunch_auction (hardening)',
      (exists (select 1 from pg_proc where proname='relaunch_auction'))),
    ('00041', 'RPC is_restricted',
      (exists (select 1 from pg_proc where proname='is_restricted'))),
    ('00042', 'superficie_m2 en Inmuebles (categoría)',
      (exists (select 1 from public.categories where slug='alquileres' and required_fields::text like '%"superficie_m2"%'))),
    ('00043', 'saved_searches.fields (columna)',
      (exists (select 1 from information_schema.columns where table_schema='public' and table_name='saved_searches' and column_name='fields'))),
    ('00044', 'tabla site_visits',
      (to_regclass('public.site_visits') is not null)),
    ('00044', 'RPC admin_metrics',
      (exists (select 1 from pg_proc where proname='admin_metrics'))),
    ('00045', 'RPC auction_bid_history',
      (exists (select 1 from pg_proc where proname='auction_bid_history')))
)
select mig,
       objeto,
       case when existe then 'OK' else 'FALTA' end as estado
from checks
order by mig, objeto;
